### ISSUE TITLE
[Developer Issue] Lets rename WEC-Sim 'master' branch to 'main'

### ISSUE THREAD

**Issue by dav-og** [WEC-Sim/WEC-Sim#1215]
**Project**
WEC-Sim

**Describe the issue**
In alignment with our ongoing efforts to foster diversity, equity, inclusion, and accessibility (DEIA) in our community, I propose that we rename our default branch from 'master' to 'main'. This change is a step towards removing language that may be considered exclusive or insensitive, and it reflects a broader shift in the tech community towards more inclusive terminology.

Several leading organizations and many open-source projects have already embraced this change, recognizing the importance of language in creating an inclusive environment. By renaming our default branch, we not only align ourselves with these best practices but also send a clear message about our values and commitment to DEIA.

For more information see: https://github.com/github/renaming

Cheers,
Dave

@akeeste:

I'm reopening this issue because in reviewing a PR I noticed there's a few outstanding things to complete:
- [x] CI tests are not running on the main branch, e.g. #1221 did not have any checks run when it went into main. All GitHub workflows (3) need to be updated to reference the 'main' branch instead of master #1235
- [x] Update WEC-Sim Applications repo branch name
- [x] Update WEC-Sim/MoorDyn branch name
- [x] Merge PR updating the WEC-Sim Applications CI workflows WEC-Sim/WEC-Sim_Applications#59
- [x] Update all references to the github repo trees, e.g. "https://github.com/WEC-Sim/WEC-Sim/tree/master" to "https://github.com/WEC-Sim/WEC-Sim/tree/main" (for applications repo too). Fortunately if unchanged these URLs DO redirect to the main branch automatically, but we should still update them  #1235
- [x] Update all references to the built documentation. This is a MAJOR change and will break any URL to WEC-Sim documentation that we've distributed in the past. Ideally our old URLs could redirect but I don't know how to do that currently. - MT: In #1235, a redirect was added from `master/index.html` to `main/index.html`. Note, this won't catch any of the old paths below `master/index.html`, they will just 404.
- [x] update organization setting to default future repos to main

PR is forthcoming to do 1, 4 above ✔️ (See #1235, #1240, #1241 and https://github.com/WEC-Sim/WEC-Sim_Applications/pull/59)

**Comment by kmruehl** [comment]
@dav-og I agree, this is something I've wanted to do for a while. Making this change will have some downstream impacts that we need to address, so I'd like to make sure the rest of the team is aware prior to making this change. Thanks for the suggestion!

**Comment by akeeste** [comment]
I'm reopening this issue because there's a few outstanding things to complete:
- CI tests are not running on the main branch, e.g. #1221 did not have any checks run when it went into main
- all github workflows (3) need to be updated to reference the 'main' branch instead of master

When doing the above, there are some merge conflicts from #1221 that need to be fixed

**Comment by H0R5E** [comment]
I don't have write permissions on https://github.com/WEC-Sim/MoorDyn, so I can't update that branch name, unfortunately.

**Comment by akeeste** [comment]
@H0R5E Sounds good about the documentation link, we'll keep that in mind for the future. Thank you for your help!

@kmruehl can you update the branch name on WEC-Sim/MoorDyn for completion of this issue?
